### ISSUE TITLE
Function docstrings are not recognized properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tallforasmurf/byteplay#4]
```
Function docstrings are not recognized properly (module dosctrings work fine).
In my special case (test case code below) docstring seems to be loaded with 
LOAD_CONST 1, however string in question is constant with index 0. 

Test case code:
def fn():
    '''
    im a ghosty docstring
    '''
```

Original issue reported on code.google.com by `roxaz...@gmail.com` on 28 Oct 2012 at 2:18

**Comment by tallforasmurf** [comment]
I don't see any problem.

    def ds():
        '''I'm a ghosty docstring'''
        pass
    dsc = Code.from_code(ds.__code__)
    dsc.docstring
    "I'm a ghosty docstring" <-- so, picked it up correctly from code.co_consts
    dsnew = dsc.to_code()
    dsnew.co_consts
    ("I'm a ghosty docstring", None) <-- put it back as co_consts[0]
    printcodelist(dsnew)
    3           1 LOAD_CONST           None <-- so, using co_consts[1] for None
                2 RETURN_VALUE
